# Generated by Django 3.2.12 on 2022-08-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_path',
            field=models.FileField(default='', upload_to='media/image/%Y/%m', verbose_name='图片地址'),
        ),
    ]
