# Generated by Django 3.2.12 on 2022-08-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_photo_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_path',
            field=models.CharField(default='', max_length=500, verbose_name='图片地址'),
        ),
    ]
