# Generated by Django 3.2.12 on 2022-08-06 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_photo_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('path', models.CharField(max_length=30, verbose_name='路径')),
                ('type', models.CharField(default='电影', max_length=30, verbose_name='类型')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资源路径',
                'verbose_name_plural': '资源路径',
                'db_table': 'path',
            },
        ),
    ]
