# Generated by Django 3.2.12 on 2022-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
