# Generated by Django 3.2.12 on 2022-08-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_path_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
